### ISSUE TITLE
Noob question: is it possible to give parts a "name" and a material / color when exporting to STEP?

### ISSUE THREAD

**Issue by maelp** [raydeleu/ReplicadManual#8]
I think STEP files can contain some form of metadata like color, and perhaps part names, would it be possible to defined those in replicad so that they are available when exporting?

**Comment by raydeleu** [comment]
I performed a litte test but have to disappoint you. I exported the shapes I created in the `shapeArray` below. If you provide a name to the shape, the resulting export will contain a step file with the same name. But neither the colour or the part name are contained in the data of the STEP file itself. The original file can be found at https://github.com/raydeleu/ReplicadManual/blob/main/models/tinkercad.js. I just added names to the first two shapes. I performed the export in the Workbench. The export consists of a zip file that contains a separate STEP file for each of the 23 shapes.  

``` javascript
let shapeArray = [
{shape: stdCylinder, color:"orange", name: "stdCylinder"}
,{shape: stdBox, color: "red", name: "stdBox"}
,{shape: stdSphere, color: "blue"}
,{shape:stdRoof, color: "green"}
,{shape:stdHex, color: "darkblue"}
,{shape:stdCone, color: "purple"}
,{shape:piramid, color: "yellow"}
,{shape:halfDome, color: "fuchsia"}
,{shape:cheese, color: "darkblue"}
,{shape:parabol, color: "white"}
,{shape:icosahedron, color: "red"}
,{shape:squareRing, color: "orange"}
,{shape:halfPipe, color: "lightblue"}
,{shape:donut, color: "blue"}
,{shape:capsule, color: "white"}
,{shape:text, color: "green"}
,{shape:roundedCube, color: "purple"}
,{shape:octPilar, color: "orange"}
,{shape:approxPiramidExtrude, color: "yellow"}
,{shape:approxPiramidLoft, color: "yellow"}  
,{shape:spinner, color: "fuchsia"}
,{shape:makeBall, color: "blue"}
,{shape:clover, color: "green"}
]
return shapeArray}
```

**Comment by maelp** [comment]
Another question : do you know if "copying a shape" rather than creating it again from scratch will allow .STEP export to "deduplicate it" and make the export file smaller?

**Comment by raydeleu** [comment]
If you copy a shape you create a new shape. On export Replicad produces a STEP file for each shape that is returned to the Visualizer or Workbench, so I would expect that it makes no difference in the file size. A quick experiment with two (almost) identical shapes resulted in an STEP export of 61kb, creating a copy of one of the shapes resulted in a STEP export of 91kb. So this seems to confirm my assumption. Obviously there is no magic behind the scenes that identifies that the shapes are identical. 

![image](https://github.com/raydeleu/ReplicadManual/assets/38007983/9abd9017-52af-4e29-a5f9-c12e7310cdb1)

Perhaps I misunderstood what you are trying to achieve. You can perform the experiment in the [Workbench](https://studio.replicad.xyz/workbench).

**Comment by maelp** [comment]
Thanks!
